### ISSUE TITLE
Custom outline on totes

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare-pro#7] opened 2016-11-24 00:30 UTC
When a custom color outlines is applied to buttons, they're applied to totes as well.

**Comment by DustinWStout** [comment] 2016-11-28 23:44
Also, custom color outlines stick around on hover even if your hover state is something other than custom color outlines.

**Comment by Nicholas-Cardot** [comment] 2016-12-26 05:02
This is a duplicate of an issue with more thorough documentation on the Core github page.

**Closed by Nicholas-Cardot** 2016-12-26 05:02 UTC
Labels: Bug/Glitch
